# Generated by Django 4.2.3 on 2023-07-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
        ('common', '0003_alter_photocomment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
